using Microsoft.CodeAnalysis.Text;

namespace Tests.CodeGenerator.ManagedWithDefaultConstructor.SingleObject;

static public class ExpectedSource
{
    static public (String filename, SourceText source) Handler
    {
        get
        {
            return (HANDLER_FILENAME, s_HandlerSource!);
        }
    }

    static public readonly SourceText s_HandlerSource = SourceText.From(text: HANDLER_SOURCE,
                                                                        encoding: Encoding.UTF8);

    public const String HANDLER_FILENAME = @"Narumikazuchi.Generators.ByteSerialization.Core\Narumikazuchi.Generators.ByteSerialization.Generators.SerializableGenerator\Narumikazuchi.Generated.Internals.ByteSerialization.Handler.Person.g.cs";

    public const String HANDLER_SOURCE = @"//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#pragma warning disable
#nullable disable

using System;
using System.Reflection;
using System.Reflection.Emit;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;
using System.Threading;

namespace Narumikazuchi.Generated.Internals.ByteSerialization;

public partial interface IAssemblyHandler_TestProject : Narumikazuchi.Generators.ByteSerialization.ISerializationHandler<Person>
{
    [CompilerGenerated]
    UInt32 Narumikazuchi.Generators.ByteSerialization.ISerializationHandler<Person>.Deserialize(ReadOnlySpan<Byte> buffer, out Person result)
    {
        var pointer = sizeof(Int32);
        result = default(Person);
        if (buffer[pointer++] == 0x1)
        {
            var _var0 = Unsafe.As<Byte, Narumikazuchi.Generators.ByteSerialization.TypeIdentifier>(ref MemoryMarshal.GetReference(buffer[pointer..]));
            pointer += Unsafe.SizeOf<Narumikazuchi.Generators.ByteSerialization.TypeIdentifier>();
            if (_var0 != Narumikazuchi.Generators.ByteSerialization.TypeIdentifier.CreateFrom(typeof(Person)))
            {
                throw new Narumikazuchi.Generators.ByteSerialization.WrongTypeDeserialization(typeof(Person));
            }
            var _var1 = default(String);
            if (buffer[pointer++] == 0x1)
            {
                var _var2 = Unsafe.As<Byte, Narumikazuchi.Generators.ByteSerialization.TypeIdentifier>(ref MemoryMarshal.GetReference(buffer[pointer..]));
                pointer += Unsafe.SizeOf<Narumikazuchi.Generators.ByteSerialization.TypeIdentifier>();
                if (_var2 != Narumikazuchi.Generators.ByteSerialization.TypeIdentifier.CreateFrom(typeof(String)))
                {
                    throw new Narumikazuchi.Generators.ByteSerialization.WrongTypeDeserialization(typeof(String));
                }
                var _var3 = Unsafe.As<Byte, Int32>(ref MemoryMarshal.GetReference(buffer[pointer..]));
                pointer += Unsafe.SizeOf<Int32>();
                _var1 = new String(MemoryMarshal.Cast<Byte, Char>(buffer[pointer..(pointer + _var3)]));
                pointer += _var3;
            }
            else
            {
                pointer += Unsafe.SizeOf<Narumikazuchi.Generators.ByteSerialization.TypeIdentifier>();
            }
            var _var4 = default(String);
            if (buffer[pointer++] == 0x1)
            {
                var _var5 = Unsafe.As<Byte, Narumikazuchi.Generators.ByteSerialization.TypeIdentifier>(ref MemoryMarshal.GetReference(buffer[pointer..]));
                pointer += Unsafe.SizeOf<Narumikazuchi.Generators.ByteSerialization.TypeIdentifier>();
                if (_var5 != Narumikazuchi.Generators.ByteSerialization.TypeIdentifier.CreateFrom(typeof(String)))
                {
                    throw new Narumikazuchi.Generators.ByteSerialization.WrongTypeDeserialization(typeof(String));
                }
                var _var6 = Unsafe.As<Byte, Int32>(ref MemoryMarshal.GetReference(buffer[pointer..]));
                pointer += Unsafe.SizeOf<Int32>();
                _var4 = new String(MemoryMarshal.Cast<Byte, Char>(buffer[pointer..(pointer + _var6)]));
                pointer += _var6;
            }
            else
            {
                pointer += Unsafe.SizeOf<Narumikazuchi.Generators.ByteSerialization.TypeIdentifier>();
            }
            var _var7 = Unsafe.As<Byte, DateOnly>(ref MemoryMarshal.GetReference(buffer[pointer..]));
            pointer += Unsafe.SizeOf<DateOnly>();
            var _var8 = Unsafe.As<Byte, Guid>(ref MemoryMarshal.GetReference(buffer[pointer..]));
            pointer += Unsafe.SizeOf<Guid>();
            result = new Person()
            {
                FirstName = _var1,
                LastName = _var4,
                DateOfBirth = _var7,
                CustomerId = _var8,
            };
        }
        else
        {
            pointer += Unsafe.SizeOf<Narumikazuchi.Generators.ByteSerialization.TypeIdentifier>();
        }
        return (UInt32)pointer;
    }

    [CompilerGenerated]
    Int32 Narumikazuchi.Generators.ByteSerialization.ISerializationHandler<Person>.GetExpectedArraySize(Person value)
    {
        var size = sizeof(Int64) + Unsafe.SizeOf<Narumikazuchi.Generators.ByteSerialization.TypeIdentifier>();
        size += sizeof(Byte) + Unsafe.SizeOf<Narumikazuchi.Generators.ByteSerialization.TypeIdentifier>();
        if (value is not null)
        {
            size += sizeof(Byte) + Unsafe.SizeOf<Narumikazuchi.Generators.ByteSerialization.TypeIdentifier>();
            if (value.FirstName is not null)
            {
                size += 4 * value.FirstName.Length;
            }
            size += sizeof(Byte) + Unsafe.SizeOf<Narumikazuchi.Generators.ByteSerialization.TypeIdentifier>();
            if (value.LastName is not null)
            {
                size += 4 * value.LastName.Length;
            }
            size += Unsafe.SizeOf<DateOnly>();
            size += Unsafe.SizeOf<Guid>();
        }
        return size;
    }

    [CompilerGenerated]
    UInt32 Narumikazuchi.Generators.ByteSerialization.ISerializationHandler<Person>.Serialize(Span<Byte> buffer, Person value)
    {
        var pointer = sizeof(Int32);
        if (value is null)
        {
            buffer[pointer++] = 0x0;
            Unsafe.As<Byte, Narumikazuchi.Generators.ByteSerialization.TypeIdentifier>(ref buffer[pointer]) = Narumikazuchi.Generators.ByteSerialization.TypeIdentifier.CreateFrom(typeof(Person));
            pointer += Unsafe.SizeOf<Narumikazuchi.Generators.ByteSerialization.TypeIdentifier>();
        }
        else
        {
            buffer[pointer++] = 0x1;
            Unsafe.As<Byte, Narumikazuchi.Generators.ByteSerialization.TypeIdentifier>(ref buffer[pointer]) = Narumikazuchi.Generators.ByteSerialization.TypeIdentifier.CreateFrom(typeof(Person));
            pointer += Unsafe.SizeOf<Narumikazuchi.Generators.ByteSerialization.TypeIdentifier>();
            if (value.FirstName is null)
            {
                buffer[pointer++] = 0x0;
                Unsafe.As<Byte, Narumikazuchi.Generators.ByteSerialization.TypeIdentifier>(ref buffer[pointer]) = Narumikazuchi.Generators.ByteSerialization.TypeIdentifier.CreateFrom(typeof(String));
                pointer += Unsafe.SizeOf<Narumikazuchi.Generators.ByteSerialization.TypeIdentifier>();
            }
            else
            {
                buffer[pointer++] = 0x1;
                Unsafe.As<Byte, Narumikazuchi.Generators.ByteSerialization.TypeIdentifier>(ref buffer[pointer]) = Narumikazuchi.Generators.ByteSerialization.TypeIdentifier.CreateFrom(typeof(String));
                pointer += Unsafe.SizeOf<Narumikazuchi.Generators.ByteSerialization.TypeIdentifier>();
                var _var0 = MemoryMarshal.AsBytes(value.FirstName.AsSpan());
                Unsafe.As<Byte, Int32>(ref buffer[pointer]) = _var0.Length;
                pointer += sizeof(Int32);
                _var0.CopyTo(buffer[pointer..]);
                pointer += _var0.Length;
            }
            if (value.LastName is null)
            {
                buffer[pointer++] = 0x0;
                Unsafe.As<Byte, Narumikazuchi.Generators.ByteSerialization.TypeIdentifier>(ref buffer[pointer]) = Narumikazuchi.Generators.ByteSerialization.TypeIdentifier.CreateFrom(typeof(String));
                pointer += Unsafe.SizeOf<Narumikazuchi.Generators.ByteSerialization.TypeIdentifier>();
            }
            else
            {
                buffer[pointer++] = 0x1;
                Unsafe.As<Byte, Narumikazuchi.Generators.ByteSerialization.TypeIdentifier>(ref buffer[pointer]) = Narumikazuchi.Generators.ByteSerialization.TypeIdentifier.CreateFrom(typeof(String));
                pointer += Unsafe.SizeOf<Narumikazuchi.Generators.ByteSerialization.TypeIdentifier>();
                var _var1 = MemoryMarshal.AsBytes(value.LastName.AsSpan());
                Unsafe.As<Byte, Int32>(ref buffer[pointer]) = _var1.Length;
                pointer += sizeof(Int32);
                _var1.CopyTo(buffer[pointer..]);
                pointer += _var1.Length;
            }
            Unsafe.As<Byte, DateOnly>(ref buffer[pointer]) = value.DateOfBirth;
            pointer += Unsafe.SizeOf<DateOnly>();
            Unsafe.As<Byte, Guid>(ref buffer[pointer]) = value.CustomerId;
            pointer += Unsafe.SizeOf<Guid>();
        }
        Unsafe.As<Byte, Int32>(ref buffer[0]) = pointer;
        return (UInt32)pointer;
    }
}";
}